import Head from 'next/head'
import Navbar from '../src/components/Navbar'
import ProductCard from '../src/components/ProductCard';
import Title from '../src/components/Title';
import { getProducts } from '../src/lib/products';

export async function getStaticProps() {
  const products = await getProducts();
  return {
    props: { products },
    revalidate: parseInt(process.env.REVALIDATE_SECONDS)
  };
}

export default function Home({products}) {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main >
      <Title>Indoor Plants</Title>
      <ul className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 p-10">
        {products.map((product) => (
          <li key={product.id}>
            <ProductCard product={product} />
          </li>
        ))}
      </ul>
      </main>
    </div>
  )
}
